---
- hosts: ["airgap"]
  become: true
  vars:
    direct_download: false
    enable_airgap_object: false
    default_nke_airgap_version: 2.8.0
    default_nke_airgap_site_folder: /release/nke/2.8.0
    default_nke_airgap_folder: /Volumes/dell-r330/Packages/Nutanix/nkp/2.8.0
    default_object_airgap_folder: /Volumes/dell-r330/Packages/Nutanix/object/3.6
  roles:
    - dimMaryanto93.ntnx_airgap
      